name: CI ARM64

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-arm64:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v1
    - name: Test
      run: |
            docker run --rm -v ${{ github.workspace }}:/io:rw --workdir=/io \
            arm64v8/ubuntu \
            bash -exc 'apt-get update && \
            apt install -y wget tar git && \
            wget https://go.dev/dl/go1.16.15.linux-arm64.tar.gz && \
            tar -C /usr/local -xzf go1.16.15.linux-arm64.tar.gz && \
            export PATH=$PATH:/usr/local/go/bin && \
            go version && \
            echo " LINT " && \
            make dependabot-check license-check lint vanity-import-check && \
            make build && \
            make check-clean-work-tree && \
            echo " test-race " && \
            make test-race && \
            echo " test-coverage " && \
            make test-coverage && \
            deactivate'
            
  compatibility-test-16:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v1
    - name: Test
      run: |
            docker run --rm -v ${{ github.workspace }}:/io:rw --workdir=/io \
            arm64v8/ubuntu \
            bash -exc 'apt-get update && \
            apt install -y wget tar git && \
            wget https://go.dev/dl/go1.16.15.linux-arm64.tar.gz && \
            tar -C /usr/local -xzf go1.16.15.linux-arm64.tar.gz && \
            export PATH=$PATH:/usr/local/go/bin && \
            go version && \
            make test-short && \
            deactivate'
        
  compatibility-test-17:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v1
    - name: Test
      run: |
            docker run --rm -v ${{ github.workspace }}:/io:rw --workdir=/io \
            arm64v8/ubuntu \
            bash -exc 'apt-get update && \
            apt install -y wget tar git && \
            wget https://go.dev/dl/go1.17.8.linux-arm64.tar.gz && \
            tar -C /usr/local -xzf go1.17.8.linux-arm64.tar.gz && \
            export PATH=$PATH:/usr/local/go/bin && \
            go version && \
            make test-short && \
            deactivate'      
